version: '3.1'
services:
  backend:
    restart: always
    build: ./employe
    container_name: backend
    working_dir: /app
    volumes:
      - ./employe:/app
      #- ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    links:
      - 'db'
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
  db:
    image: postgres:11.2
    container_name: db
    restart: always
    volumes:
      - ./db_data/data:/var/lib/postgresql/data
      - ./db_data/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db_data/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
