version: '3.1'
services:
  # frontend:
  #   build: ./webui
  #   restart: always
  #   container_name: frontend
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./webui:/var/www/html
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - backend
  #   links:
  #     - 'backend'
  backend:
    restart: always
    build: ./employe
    container_name: backend
    working_dir: /app
    volumes:
      - ./employe:/app:z
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - db
    links:
      - 'db'
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
  db:
    image: postgres:11.2
    container_name: db
    restart: always
    volumes:
      - ./db_data/data:/var/lib/postgresql/data
      - ./db_data/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db_data/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
